# Generated by Django 2.2.6 on 2020-04-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('num_pages', models.IntegerField(default=200)),
                ('date_published', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
