# Generated by Django 2.2.6 on 2020-04-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200408_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='tags',
        ),
    ]
